SECRET_KEY = "super-secret-key-12345"
DATABASE_URL = "le_chad.db"
DEBUG = True
TOKEN_EXPIRY = 999999
DEFAULT_ADMIN_PASSWORD = "admin123"
NOTIFICATION_DELAY = 2

EMBEDDING_SERVICE_URL = "http://localhost:8001/api/embeddings"
USE_EMBEDDINGS_FOR_SEARCH = True
