"""
Stage 5: Git operations — branch, commit, push, and create PR via gh CLI.
"""

import re
import subprocess
from pathlib import Path


def _run_git(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git"] + args,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=30,
    )


def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:60]


def create_branch(plan: dict, repo_path: Path) -> str:
    """Create and checkout a new branch for this plan."""
    branch_name = f"chadbot/{slugify(plan.get('title', 'improvement'))}"

    result = _run_git(["checkout", "-b", branch_name], repo_path)
    if result.returncode != 0 and "already exists" in result.stderr:
        _run_git(["checkout", branch_name], repo_path)

    return branch_name


def commit_changes(plan: dict, repo_path: Path) -> bool:
    """Stage all changes and commit."""
    _run_git(["add", "-A"], repo_path)

    title = plan.get("title", "chadbot improvement")
    summary = plan.get("summary", "")
    inspired_by = plan.get("inspired_by", "")

    msg = f"{title}\n\n{summary}"
    if inspired_by:
        msg += f"\n\nInspired by: {inspired_by}"
    msg += "\n\nGenerated by chadbot feature-builder agent."

    result = _run_git(["commit", "-m", msg], repo_path)
    return result.returncode == 0


def push_branch(branch_name: str, repo_path: Path) -> bool:
    """Push the branch to origin."""
    result = _run_git(["push", "-u", "origin", branch_name], repo_path)
    return result.returncode == 0


def create_pr(plan: dict, branch_name: str, repo_path: Path) -> dict:
    """Create a pull request via gh CLI."""
    title = plan.get("title", "chadbot improvement")
    summary = plan.get("summary", "")
    inspired_by = plan.get("inspired_by", "")
    changes = plan.get("changes", [])

    body_parts = [
        f"## Summary\n\n{summary}",
    ]
    if inspired_by:
        hn_url = plan.get("hn_url", "")
        body_parts.append(f"## Inspired by\n\n[{inspired_by}]({hn_url})")
    if changes:
        body_parts.append("## Files changed\n")
        for c in changes:
            body_parts.append(f"- `{c['file']}`: {c['description']}")

    body_parts.append("\n---\n*Generated by chadbot feature-builder agent.*")
    body = "\n\n".join(body_parts)

    result = subprocess.run(
        ["gh", "pr", "create", "--title", title, "--body", body],
        cwd=repo_path,
        capture_output=True,
        text=True,
        timeout=30,
    )

    if result.returncode == 0:
        pr_url = result.stdout.strip()
        return {"status": "created", "url": pr_url}
    else:
        return {"status": "failed", "reason": result.stderr.strip()}


def checkout_main(repo_path: Path) -> None:
    """Return to main branch."""
    _run_git(["checkout", "main"], repo_path)
